version: '3.8'

services:
  jellyfinplus:
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE_NAME}:${VERSION}
    ports:
      - "8080:8080"
    environment:
      - JELLYFIN_BASE_URL=${JELLYFIN_BASE_URL}
      - JELLYFIN_TOKEN=${JELLYFIN_TOKEN}
      - JELLYFIN_USER_NAME=${JELLYFIN_USER_NAME}
      - TRANSMISSION_BASE_URL=${TRANSMISSION_BASE_URL}
      - TRANSMISSION_USERNAME=${TRANSMISSION_USERNAME}
      - TRANSMISSION_PASSWORD=${TRANSMISSION_PASSWORD}

