spring:
  application:
    name: jellyfinplus

logging:
  level:
    root: INFO
    com.davidperezmillan.jellyfinplus: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

transmission:
  baseUrl: ${TRANSMISSION_BASE_URL}
  username: ${TRANSMISSION_USERNAME}
  password: ${TRANSMISSION_PASSWORD}
